# Schema: https://json.schemastore.org/github-action.json
name: java-client

description: Build OpenAPI Java client for given parameters.

branding:
  color: black
  icon: book

inputs:
  spicedb-version:
    required: true
    description: 'The SpiceDB version to use'
  release-version:
    required: true
    description: NPM artifact version to use
  generator:
    required: true
    description: NPM generator to use

runs:
  using: 'composite'
  steps:
    # See https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript.md
    - name: Generate Typescript ${{ matrix.java-version }} client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: typescript
        # FIXME base url from prepare
        openapi-url: "https://raw.githubusercontent.com/authzed/authzed-go/refs/tags/${{ inputs.spicedb-version }}/proto/apidocs.swagger.json"
        config-file: cfg/typescript.yml
        command-args: -p "npmName=authzed-http-client-${{ inputs.generator }}" -p "npmVersion=${{ inputs.release-version }}"
