name: Build main

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  java-client:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        java-version: [17, 21]
        java-http-lib: [restclient, okhttp-gson]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Run java client build composite action'
        uses: ./.github/actions/main-java
        with:
          java-version: ${{ matrix.java-version }}
          java-http-lib: ${{ matrix.java-http-lib }}
