name: Build main

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  java-client:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        java-version: [17, 21]
        java-http-lib: [restclient, okhttp-gson]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read SpiceDB version file
        shell: bash
        run: echo "SPICEDB_VERSION=$(cat spicedb.version)" >> $GITHUB_ENV

      - name: "Run java client build / SpiceDB: ${{ env.SPICEDB_VERSION }} / Java: ${{ matrix.java-version}} / HTTP lib: ${{ matrix.java-http-lib }}"
        uses: ./.github/actions/main-java
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
