name: Build main

on:
  push:
    branches: ["main"]

jobs:
  java-build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        java-version: [21]
        java-http-lib: [restclient]

    # TODO fully implement workflow
    steps:
      - uses: actions/checkout@v4
      - name: Generate Java (Spring RestClient) client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: java
          openapi-url: "https://raw.githubusercontent.com/authzed/authzed-go/refs/tags/v1.1.0/proto/apidocs.swagger.json"
          config-file: cfg/java.yml
          # TODO param for authzed version
          command-args: -p "artifactVersion=0.0.0" -p "library=restclient"

      - name: Switch into generated java client working directory
        run: |
          cd java-client