name: Build main

on:
  push:
    branches: ["main"]

# TODO fully implement workflow
jobs:
  java-client:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        java-version: [17, 21]
        java-http-lib: [restclient, okhttp-gson]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Java (Spring RestClient) client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: java
          openapi-url: "https://raw.githubusercontent.com/authzed/authzed-go/refs/tags/v1.1.0/proto/apidocs.swagger.json"
          config-file: cfg/java.yml
          # TODO param for authzed version
          command-args: -p "artifactVersion=0.0.0" -p "library=${{ matrix.java-http-lib }}"

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      # the name of maven input directory is derived from openapi action output
      - name: Run Maven build
        run: mvn -B package --file java-client/pom.xml

      - name: Prepare upload
        run: mkdir upload && cp -R java-client/target/*.jar upload

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Java ${{ matrix.java-version }} client library (${{ matrix.java-http-lib }})
          path: upload
