name: main

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  java-client:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        java-version: [17, 21]
        java-http-lib: [restclient, okhttp-gson]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      - name: Read SpiceDB version file
        shell: bash
        run: echo "SPICEDB_VERSION=$(cat spicedb.version)" >> ${GITHUB_ENV}

      # consecutive numbers versioning workflow
      - name: Get next calver artifact version
        uses: reecetech/version-increment@2024.10.1
        id: java-artifact-version
        with:
          scheme: semver
          increment: patch

      - name: Create target Java artifact version
        shell: bash
        run: echo "JAVA_ARTIFACT_VERSION=${{ matrix.java-version }}-${{ env.SPICEDB_VERSION }}-${{ steps.java-artifact-version.outputs.version }}" >> ${GITHUB_ENV}

      - name: "Run java client build / SpiceDB: ${{ env.SPICEDB_VERSION }} / Java: ${{ matrix.java-version}} / HTTP lib: ${{ matrix.java-http-lib }}"
        uses: ./.github/actions/java-client
        with:
          release-version: ${{ env.JAVA_ARTIFACT_VERSION }}
          snapshot: true

      - name: "Publish java client snapshot to GitHub packages / SpiceDB: ${{ env.SPICEDB_VERSION }} / Java: ${{ matrix.java-version}} / HTTP lib: ${{ matrix.java-http-lib }}"
        uses: ./.github/actions/java-publish-client-snapshot
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
